# -*- coding: utf-8 -*-
"""PythonProiect.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/147CfP7k-Qb47ZSfPfjRxV_ohfKOGCvRS
"""

import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("cardio_train.csv",sep=';')
df.head()
df.info()

df.head()

from matplotlib import rcParams
rcParams['figure.figsize'] = 11, 8
df['years'] = (df['age'] / 365).round().astype('int')
sns.countplot(x='gender', hue='cholesterol', data = df, palette="Set1");

#sns.countplot(x='age', hue='cholesterol', data = df, palette="Set1");
sns.kdeplot(df['years'],df['cholesterol'],shade =True)

sns.countplot(x='years', hue='cholesterol', data = df, palette="Set2");

df.drop(df[(df['ap_hi'] > df['ap_hi'].quantile(0.975)) | (df['ap_hi'] < df['ap_hi'].quantile(0.025))].index,inplace=True)
df.drop(df[(df['ap_lo'] > df['ap_lo'].quantile(0.975)) | (df['ap_lo'] < df['ap_lo'].quantile(0.025))].index,inplace=True)

from sklearn.linear_model import LinearRegression as lr
model =lr(copy_X=True, fit_intercept=True, normalize=False)
X = df['years'][:, None]
y = df['age']

temp =model.fit(X,y)
print(temp.score(X,y))
print(model.coef_)
print(model.intercept_)
z= model.predict(X)

plt.scatter(X,y)
plt.plot(X,z,color='red')

corr = df.corr()
cmap = sns.diverging_palette(220,221, as_cmap=True)
# Generate a mask for the upper triangle
mask = np.zeros_like(corr, dtype=np.bool)
mask[np.triu_indices_from(mask)] = True

# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(11, 9))
# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(corr, mask=mask, cmap=cmap, vmax=.3, center=0,annot = True,
            square=False, linewidths=.75, cbar_kws={"shrink": .75});

"""Se pot observa mai multe corelatii dupa cum urmeaza : 
Cea mai mare fiind dintre ani si varsta ( cu o valoare de 1 este o regresie liniara perfecta fiind vorba despre acelai lucru scris sub o alta forma, dar aceasta nu poate fi luata in considerare, fiind un lucru evident.

Urmatoarea corelatie ca importanta este Presinua sistolica cu presiunea diastolica ( Indice de corelatie = 0.7 -> corelatie puternica ) Acest lucru rezulta din faptul ca sunt masuratori ale inimilor pacientilor, iar acestea ar trebui sa ai o legatura destul de puternica de cele mai multe ori 

De mentionat mai sunt si corelatiile glucoza cu colesterol, de unde rezulta o legatura slaba, dar prezenta intre cele doua valori 

Alte si mai slabe dar de urmarit sunt cele care depasesc valoarea de 0.2, dar nu merita atentie suplimentara. 
"""

from sklearn.linear_model import LinearRegression as lr
model =lr(copy_X=True, fit_intercept=True, normalize=False)
X = df['ap_hi'][:, None]
y = df['ap_lo']

temp =model.fit(X,y)
print(temp.score(X,y))
print(model.coef_)
print(model.intercept_)
z= model.predict(X)

plt.scatter(X,y)
plt.plot(X,z,color='red')

"""Asadar am si reprezentat grafic cea mai puternica relatie, cea dintre presiunea sistolica si diastolica si se poate observa si dreapta de regresie cu o forma crescatoare iar volorile de panta si intercept fiind  0.41853432 respectiv
28.404520315511483 de unde ar rezulta formula
Presiunea Sistolica ( mai mare) = Presiune diastolica * 0.41853432 + 28.404520315511483, formula valida pentru aproximativ 50% dintre subiecti supusi testarii, in urma filtrarii pe valorile extreme.
"""